version: "3.9"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    depends_on:
      - database

  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
